UPDATE EMPRE_SA.dbo.Categoria_Cuentas
SET descripcion=N'CAJA 1'
WHERE id_categoria=1;
-- INSERT INTO EMPRE_SA.dbo.Categoria_Cuentas(descripcion) VALUES(N'CAJA 1');
INSERT INTO EMPRE_SA.dbo.Categoria_Cuentas
(descripcion)
VALUES(N'CAJA 2');
INSERT INTO EMPRE_SA.dbo.Categoria_Cuentas
(descripcion)
VALUES(N'CAJA CHICA');
INSERT INTO EMPRE_SA.dbo.Categoria_Cuentas
(descripcion)
VALUES(N'CAJA GENERAL');
INSERT INTO EMPRE_SA.dbo.Categoria_Cuentas
(descripcion)
VALUES(N'BANCO');
INSERT INTO EMPRE_SA.dbo.Categoria_Cuentas
(descripcion)
VALUES(N'FACTURAS_CONTRATOS');
INSERT INTO EMPRE_SA.dbo.Categoria_Cuentas
(descripcion)
VALUES(N'FACTURAS_VENTAS');
INSERT INTO EMPRE_SA.dbo.Categoria_Cuentas
(descripcion)
VALUES(N'OBLIGACIONES');
